project:
  id: 4549361d-fd27-4048-9959-ccde251c34f7
  name: Paradigmata
  description: >-
    Repository layout paradigms and writing conventions for LLM agents
  authors:
    - name: Kvn Dtrx
      mail: kvn.dtrx+git@protonmail.ch
  license:
    type: MIT
    year: 2026
    file: LICENSE.txt
forges:
  github:
    url: https://github.com/kvn-dtrx/paradigmata
    visibility: public
